### ISSUE TITLE
mk_sap component Unhandled exception (Function Name in function_lookup must be a String)

### ISSUE THREAD

**Issue by ajayctrls** [piersharding/python-sapnwrfc#10]
Hi Piersharding,

OS : SLES 12 SP2
SAP NW RFC : 7.20
Component : mk_sap

Error on line 199 (mk_sap): 

198 : def query(what, params, debug = False):
199 :     fd = conn.discover(what)

# --------------- --------------- Error ---------------------------------- 
ERROR: Unhandled exception (Function Name in function_lookup must be a String)
<<<sap_state:sep(9)>>>
localhost       Unhandled exception (Function Name in function_lookup must be a String)
# --------------- --------------- End ---------------------------------- 

Please suggent what can be done.

Thanks

Ajay K

**Comment by ajayctrls** [comment]
sap.cfg content

cfg = [
{
    'ashost':   'localhost',
    'sysnr':    '11',
    'client':   '000',
    'user':     'USR',
    'passwd':   'pass',
    'trace':    '3',
    'loglevel': 'warn',
    'lang':     'EN',
},

**Comment by piersharding** [comment]
Hi -

It sounds like the 'what' in conn.discover(what) is not a string - it should be something like:
conn.discover("RFC_READ_TABLE")

Cheers,
Piers.

**Comment by ajayctrls** [comment]
Hi Piers,

Thanks for your information.

I am debugging and get back to you right away.

Thanks

Ajay K

**Comment by ajayctrls** [comment]
Hi Piers,

First call is made with “BAPI_XMI_LOGON” as what parameter.
This call returns Unhandled exception.

I have changed that call with try block:

    try:
        fd = conn.discover(what)
    except sapnwrfc.RFCCommunicationError as e:
        sys.stdout.write('NWRFC Connection Error %s\n' % e)
    except Exception as e:
        sys.stdout.write('Exception :%s\n' % e)

Input :

What = BAPI_XMI_LOGON

Output :

Exception :Function Name in function_lookup must be a String

Please suggest.

Python version is 3.4.

Thanks

Ajay K

**Comment by ajayctrls** [comment]
Hi Piers,

On another note, what is the most suitable OS for compiling this plugin.

Please keep in mind : Target system for binary use will SLES 12 SP2

Thanks

Ajay K

**Comment by ajayctrls** [comment]
Hi Piers,

I have also found there some dependencies:
1. python-devel-3.4
2. python-PyYAML-3.4
3. yaml
4. sapnwrfc-0.19 (from check_mk link)

Please suggest, if I am missing or skipping any dependencies.

Thanks

Ajay K

**Comment by ajayctrls** [comment]
Hi Piers,

One last question, what Python version is most suitable for your plugin compilation and usage?

Thanks

Ajay K

**Comment by ajayctrls** [comment]
Hi Piers,

Do you need any other information to suggest me a change or correction?

Thanks

Ajay K

**Comment by piersharding** [comment]
Hi -
I have used Python 3.6.5 on Ubuntu 18.04.

Cheers.

**Comment by ajayctrls** [comment]
Hi Piers,

I have given up on troubleshooting python-sapnwrfc.

I have implemented PyRFC.

Thanks

Ajay K

**Comment by basmati-bn** [comment]
Hi, I have the same error (ERROR: Unhandled exception (Function Name in function_lookup must be a String).
Any progess on this ? I would be interested in knowing how you handled the switch to pyRFC.

Thanks, Wolfgang
