### ISSUE TITLE
sapnwrfc on pypi still needed?

### ISSUE THREAD

**Issue by bsrdjan** [piersharding/python-sapnwrfc#11]
Hello Pierse,

Is https://pypi.org/project/sapnwrfc/ still active and if not would you mind removing it from PyPI?

SAP/PyRFC shall be published on PyPI soon and sapnwrfc is one of package name candidates. 

No problem at all also if you want to keep the sapnwrfc on PyPI, just please let me know, to continue naming brainstorming :)

Thanks and regards,
Srdjan

**Comment by piersharding** [comment]
Hi Srdjan,

Yes the project is still in use, and aligns with perl-sapnwrfc, php-sapnwrfc, ruby-sapnwrfc, and RSAP, so I would prefer to maintain the namespace.
Cheers,
Piers.

**Comment by bsrdjan** [comment]
Thanks.
