### ISSUE TITLE
Handling of unicode strings

### ISSUE THREAD

**Issue by guettli** [piersharding/python-sapnwrfc#4]
My issue was, that the interpreter gets into an endless loop, if I submit latin1 encoded strings in rfc calls.

Here is a modified version which accepts unicode strings.

Up to now I get this message:
 RFC FUNCTION CALL ERROR: RfcSetChar invalid Input value type: u'...'

BTW, it would be nice if the Tab/Space mix in nwsaprfcutil.c could be cleaned up.

``` diff
diff --git a/src/nwsaprfcutil.c b/src/nwsaprfcutil.c
index 79ede30..379ffc2 100644
--- a/src/nwsaprfcutil.c
+++ b/src/nwsaprfcutil.c
@@ -152,18 +152,19 @@ SAP_UC * u8to16c(char * str) {

 SAP_UC * u8to16(PyObject *str) {
   RFC_RC rc;
-   RFC_ERROR_INFO errorInfo;
-   SAP_UC *sapuc;
-   unsigned sapucSize, resultLength;
-
+  RFC_ERROR_INFO errorInfo;
+  SAP_UC *sapuc;
+  unsigned sapucSize, resultLength;
+  if (PyUnicode_Check(str)) {
+    str=PyUnicode_AsUTF8String(str);
+  } 
   sapucSize = PyString_Size(str) + 1;
   sapuc = mallocU(sapucSize);
   memsetU(sapuc, 0, sapucSize);

-   resultLength = 0;
-
+  resultLength = 0;
   rc = RfcUTF8ToSAPUC((RFC_BYTE *)PyString_AsString(str), PyString_Size(str), sapuc, &sapucSize, &resultLength, &errorInfo);
-   return sapuc;
+  return sapuc;
 }


@@ -1423,7 +1424,7 @@ void set_char_value(DATA_CONTAINER_HANDLE hcont, SAP_UC *name, PyObject * value,
   RFC_ERROR_INFO errorInfo;
    SAP_UC *p_value;

-   if (! PyString_Check(value)){
+   if (! PyString_Check(value) && !PyUnicode_Check(value)){
            SAPNW_rfc_call_error1("RfcSetChar invalid Input value type:", PyString_AsString(PyObject_Repr(value)));
        return;
    }
```

**Comment by piersharding** [comment]
Hi -

Thanks for having a look at this problem.

I've applied your patch and bumped the version to 0.16.

And I've added you as a collaborator, so you should be able to commit if you
want to.

Thanks,
Piers Harding.

On 5 October 2011 00:09, Thomas Gttler <
reply@reply.github.com>wrote:

> My issue was, that the interpreter gets into an endless loop, if I submit
> latin1 encoded strings in rfc calls.
> 
> Here is a modified version which accepts unicode strings.
> 
> Up to now I get this message:
>  RFC FUNCTION CALL ERROR: RfcSetChar invalid Input value type: u'...'
> 
> BTW, it would be nice if the Tab/Space mix in nwsaprfcutil.c could be
> cleaned up.
> 
> {{{
> diff --git a/src/nwsaprfcutil.c b/src/nwsaprfcutil.c
> index 79ede30..379ffc2 100644
> --- a/src/nwsaprfcutil.c
> +++ b/src/nwsaprfcutil.c
> @@ -152,18 +152,19 @@ SAP_UC \* u8to16c(char \* str) {
> 
>  SAP_UC \* u8to16(PyObject *str) {
>   RFC_RC rc;
> -   RFC_ERROR_INFO errorInfo;
> -   SAP_UC *sapuc;
> 
> ## \-   unsigned sapucSize, resultLength;
> -  RFC_ERROR_INFO errorInfo;
> -  SAP_UC *sapuc;
> -  unsigned sapucSize, resultLength;
> -  if (PyUnicode_Check(str)) {
> -    str=PyUnicode_AsUTF8String(str);
> -  }
>   sapucSize = PyString_Size(str) + 1;
>   sapuc = mallocU(sapucSize);
>   memsetU(sapuc, 0, sapucSize);
> 
> ## \-   resultLength = 0;
> -  resultLength = 0;
>   rc = RfcUTF8ToSAPUC((RFC_BYTE *)PyString_AsString(str),
>   PyString_Size(str), sapuc, &sapucSize, &resultLength, &errorInfo);
> -   return sapuc;
> -  return sapuc;
>   }
> 
> @@ -1423,7 +1424,7 @@ void set_char_value(DATA_CONTAINER_HANDLE hcont,
> SAP_UC *name, PyObject \* value,
>   RFC_ERROR_INFO errorInfo;
>    SAP_UC *p_value;
> -   if (! PyString_Check(value)){
> -   if (! PyString_Check(value) && !PyUnicode_Check(value)){
>          SAPNW_rfc_call_error1("RfcSetChar invalid Input value type:",
>   PyString_AsString(PyObject_Repr(value)));
>      return;
>   }
> 
> }}}
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/piersharding/python-sapnwrfc/issues/4

## 

mail/xmpp: piers@ompka.net
http://www.piersharding.com
