### ISSUE TITLE
Introspection of (deep) Structures

### ISSUE THREAD

**Issue by guettli** [piersharding/python-sapnwrfc#5]
Is it possible to introspect structures? I wrote an introspection for functions a while ago. Now I need something like this for structures, but AFAIK you only can discover functions, not structures.

**Comment by piersharding** [comment]
Hi -

If you know the name of the DDIC object then you might be able to get what
you need using RFC_GET_STRUCTURE_DEFINITION_P ?

Cheers,
Piers Harding.

On 25 May 2012 18:51, Thomas Güttler <
reply@reply.github.com

> wrote:
> 
> Is it possible to introspect structures? I wrote an introspection for
> functions a while ago. Now I need something like this for structures, but
> AFAIK you only can discover functions, not structures.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/piersharding/python-sapnwrfc/issues/5

## 

mail/xmpp: piers@ompka.net
http://www.piersharding.com

**Comment by guettli** [comment]
thank you piers, I will try it. I will post it here, if I create a reusable method for structure introspection.
